### ISSUE TITLE
Add TIDDIT cmd to version line in vcf header 

### ISSUE THREAD

**Issue by henrikstranneheim** [J35P312/TIDDIT#2]

**Comment by J35P312** [comment]
Hello! 
I have now fixed a line for the TIDDIT command in the vcf header:
TIDDITcmd="TIDDIT --sv -b few_reads"
would you be happy with that?
I made a new release 1.1.4, this time, I also updated the version tag in the TIDDIT sosurce code!

**Comment by henrikstranneheim** [comment]
Most important is that you write the version in the header 

Skickat från min iPhone

**Comment by henrikstranneheim** [comment]
You forgot to add the line according to vcf specifications, this throws errors:

TIDDITcmd="TIDDIT --sv -p 6 -o slask/ADM1059A2_lanes_8_sorted_md_brecal_tiddit -b slask/ADM1059A2_lanes_8_sorted_md_brecal.bam"

**Comment by J35P312** [comment]
woopsie daisy!
Which version are you using? I did forget the ## in version 1.1.4, but I fixed it for 1.1.5:

##TIDDITcmd="TIDDIT --sv -b /proj/sens2016003/SWEGEN/bam//AB35001299.clean.dedup.bam -o /scratch/25774/TIDDIT/AB35001299.clean.dedup.tiddit"

Or do you get any other error?
